version: "3"

services:
  geoportal:
    build: ./geoportal
    container_name: padre1-gn
    depends_on:
      - pg
    ports: 
      - "8083:8080"
    links:
      - pg
    volumes:
      - gndata-volume:/var/padre/geonetwork_datadir
    environment:
      - POSTGRES_DB_USERNAME=geonetwork
      - POSTGRES_DB_PASSWORD=geonetwork
      - DATA_DIR=/var/padre/geonetwork_datadir
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=geoportal (geonetwork)"
      - "fr.pigeo.product=Padre v1"
  pg:
    build: ./postgresql
    container_name: padre1-pg
    volumes:
      - pgdata-volume:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=postgreSQL"
      - "fr.pigeo.product=Padre v1"
  pgis:
    build: ./postgis
    container_name: padre1-postgis
    volumes:
      - postgisdata-volume:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=Postgis"
      - "fr.pigeo.product=Padre v1"
  geoserver:
    build: ./geoserver
    container_name: padre1-gs
    depends_on:
      - pgis
    ports: 
      - "8082:8080"
    links:
      - pgis
    volumes:
      - gsdata-volume:/usr/local/tomcat/webapps/ROOT/data
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=GeoServer"
      - "fr.pigeo.product=Padre v1"
  httpd:
    build: ./httpd
    container_name: padre1-httpd
    depends_on:
      - pgis
    ports:
      - "82:80"
    links:
      - pgis
    volumes:
      - wwwdata-volume:/var/www/html/
    environment:
      - APACHE_SERVERNAME=dock1.pigeo.fr
      - POSTGRES_HOST=pgis
      - POSTGRES_PORT=5432
      - POSTGRES_DEFAULTDB=geodata
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=apache2 httpd"
      - "fr.pigeo.product=Padre v1"
  commandline:
    build: ./commandlinetools
    container_name: padre1-commandlinetools
    ports:
      - "2222:22"
    links:
      - pg
      - pgis
    volumes:
      - sshd-home-volume:/home
      - wwwdata-volume:/padre/www-data
      - gsdata-volume:/padre/geoserver-data
      - /home/jean/.ssh/id_rsa.pub:/etc/authorized_keys/jean
    environment:
      - SSH_USERS=jean:1000:1000
    labels:
      - "fr.pigeo.project=Gabon-mines"
      - "fr.pigeo.container-type=sshd"
      - "fr.pigeo.product=Padre v1"

    
volumes:
  pgdata-volume:
  postgisdata-volume:
  gndata-volume:
  gsdata-volume:
  wwwdata-volume:
  sshd-home-volume:
