version: "3"

services:
  geoportal:
    build: geoportal
    depends_on:
      - pg
    ports: 
      - "8080:8080"
    links:
      - pg
    volumes:
      - gndata-volume:/var/padre/geonetwork_datadir
    environment:
      - POSTGRES_DB_USERNAME=geonetwork
      - POSTGRES_DB_PASSWORD=geonetwork
      - DATA_DIR=/var/padre/geonetwork_datadir
  pg:
    build: postgresql
    volumes:
      - pgdata-volume:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  geoserver:
    build: geoserver
    ports: 
      - "8081:8080"
    volumes:
      - gsdata-volume:/usr/local/tomcat/webapps/ROOT/data
    
volumes:
  pgdata-volume:
  gndata-volume:
  gsdata-volume:
  wwwdata-volume:
