version: '2'
volumes:
  r-mlrisk-postgisdata-volume:
    driver: local
  r-mlrisk-owncloud-volume:
    driver: local
  r-mlrisk-sshd-home-volume:
    driver: local
  r-mlrisk-gndata-volume:
    driver: local
  r-mlrisk-gsdata-volume:
    driver: local
  r-mlrisk-wwwdata-volume:
    driver: local
  r-mlrisk-geodata-volume:
    driver: local
services:
  r-mlrisk-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    expose:
    - 80:80/tcp
    - 22:22/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.http: 'true'
  r-mlrisk-SSL-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    expose:
    - 8080:8080/tcp
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.https: 'true'
  r-mlrisk-httpd:
    image: jeanpommier/padre-httpd:latest
    environment:
      APACHE_SERVERNAME: ml-risk.pigeo.fr
      POSTGRES_HOST: pgis
      POSTGRES_PORT: '5432'
      POSTGRES_DEFAULTDB: geodata
    stdin_open: true
    volumes:
    - r-mlrisk-wwwdata-volume:/var/www/html/
    tty: true
    links:
    - r-mlrisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-mlrisk-geoportal:
    image: jeanpommier/padre-geonetwork:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
      DATA_DIR: /padre/geonetwork_datadir
    stdin_open: true
    volumes:
    - r-mlrisk-gndata-volume:/padre/geonetwork_datadir
    tty: true
    links:
    - r-mlrisk-postgis:pg
    labels:
      io.rancher.container.pull_image: always
  r-mlrisk-geodash:
    image: jeanpommier/padre-geodash:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
    stdin_open: true
    volumes:
    - r-mlrisk-geodata-volume:/padre/geodata
    tty: true
    links:
    - r-mlrisk-postgis:pg
    labels:
      io.rancher.container.pull_image: always
  r-mlrisk-owncloud:
    image: jeanpommier/padre-owncloud:latest
    environment:
      OWNCLOUD_DOMAIN: ml-risk.pigeo.fr
      OWNCLOUD_SUB_URL: /owncloud
    stdin_open: true
    volumes:
    - r-mlrisk-owncloud-volume:/mnt/data
  r-mlrisk-odkaggregate:
    image: jeanpommier/padre-odkaggregate:latest
    environment:
      DB_HOSTNAME: pgis
      DB_USER: padre
      DB_PASSWORD: padre
      DB_DATABASE: geodata
      DB_SCHEMA: odk1
      DB_PORT: '5432'
      ODK_HOSTNAME: ml-risk.pigeo.fr
      ODK_PORT: '80'
    stdin_open: true
    links:
    - r-mlrisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-mlrisk-geoserver:
    image: jeanpommier/padre-geoserver:latest
    environment:
      GEOSERVER_DATA_DIR: /padre/geoserver_data
    stdin_open: true
    volumes:
    - r-mlrisk-gsdata-volume:/padre/geoserver_data
    - r-mlrisk-geodata-volume:/padre/geodata
    tty: true
    links:
    - r-mlrisk-postgis:pgis
    labels:
      fr.pigeo.container-type: GeoServer
      fr.pigeo.project: r-mlrisk-mines
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  r-mlrisk-ssh:
    image: jeanpommier/padre-commandline:latest
    environment:
      SSH_USERS: jean:1000:1000
    stdin_open: true
    volumes:
    - r-mlrisk-sshd-home-volume:/home
    - r-mlrisk-wwwdata-volume:/padre/www-data
    - r-mlrisk-geodata-volume:/padre/geodata
    - r-mlrisk-gsdata-volume:/padre/geoserver_data
    - r-mlrisk-gndata-volume:/padre/geonetwork_datadir
    - /etc/authorized_keys:/etc/authorized_keys
    tty: true
    links:
    - r-mlrisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-mlrisk-postgis:
    image: jeanpommier/padre-postgis:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    stdin_open: true
    volumes:
    - r-mlrisk-postgisdata-volume:/var/lib/postgresql/data/pgdata
    tty: true
    labels:
      io.rancher.container.pull_image: always
