version: '2'
volumes:
  r-nerisk-postgisdata-volume:
    driver: local
  r-nerisk-owncloud-volume:
    driver: local
  r-nerisk-sshd-home-volume:
    driver: local
  r-nerisk-gndata-volume:
    driver: local
  r-nerisk-gsdata-volume:
    driver: local
  r-nerisk-wwwdata-volume:
    driver: local
  r-nerisk-geodata-volume:
    driver: local
services:
  r-nerisk-lb:
    image: rancher/lb-service-haproxy:v0.6.2
    expose:
    - 80:80/tcp
    - 22:22/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.http: 'true'
  r-nerisk-SSL-lb:
    image: rancher/lb-service-haproxy:v0.6.2
    expose:
    - 8080:8080/tcp
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.https: 'true'
  r-nerisk-httpd:
    image: jeanpommier/padre-httpd:latest
    environment:
      APACHE_SERVERNAME: "$DOMAIN_URL"
      POSTGRES_HOST: pgis
      POSTGRES_PORT: '5432'
      POSTGRES_DEFAULTDB: geodata
    stdin_open: true
    volumes:
    - r-nerisk-wwwdata-volume:/var/www/html/
    tty: true
    links:
    - r-nerisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-nerisk-geoportal:
    image: jeanpommier/padre-geonetwork:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
      DATA_DIR: /padre/geonetwork_datadir
    stdin_open: true
    volumes:
    - r-nerisk-gndata-volume:/padre/geonetwork_datadir
    tty: true
    links:
    - r-nerisk-postgis:pg
    labels:
      io.rancher.container.pull_image: always
  r-nerisk-geodash:
    image: jeanpommier/padre-geodash:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
    stdin_open: true
    volumes:
    - r-nerisk-geodata-volume:/padre/geodata
    tty: true
    links:
    - r-nerisk-postgis:pg
    labels:
      io.rancher.container.pull_image: always
  r-nerisk-owncloud:
    image: jeanpommier/padre-owncloud:latest
    environment:
      OWNCLOUD_DOMAIN: "$DOMAIN_URL"
      OWNCLOUD_SUB_URL: /owncloud
    stdin_open: true
    volumes:
    - r-nerisk-owncloud-volume:/mnt/data
  r-nerisk-odkaggregate:
    image: jeanpommier/padre-odkaggregate:latest
    environment:
      DB_HOSTNAME: pgis
      DB_USER: padre
      DB_PASSWORD: padre
      DB_DATABASE: geodata
      DB_SCHEMA: odk1
      DB_PORT: '5432'
      ODK_HOSTNAME: "$DOMAIN_URL"
      ODK_PORT: '80'
    stdin_open: true
    links:
    - r-nerisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-nerisk-geoserver:
    image: jeanpommier/padre-geoserver:latest
    environment:
      GEOSERVER_DATA_DIR: /padre/geoserver_data
    stdin_open: true
    volumes:
    - r-nerisk-gsdata-volume:/padre/geoserver_data
    - r-nerisk-geodata-volume:/padre/geodata
    tty: true
    links:
    - r-nerisk-postgis:pgis
    labels:
      fr.pigeo.container-type: GeoServer
      fr.pigeo.project: r-nerisk-mines
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  r-nerisk-ssh:
    image: jeanpommier/padre-commandline:latest
    environment:
      SSH_USERS: jean:1000:1000
    stdin_open: true
    volumes:
    - r-nerisk-sshd-home-volume:/home
    - r-nerisk-wwwdata-volume:/padre/www-data
    - r-nerisk-geodata-volume:/padre/geodata
    - r-nerisk-gsdata-volume:/padre/geoserver_data
    - r-nerisk-gndata-volume:/padre/geonetwork_datadir
    - /etc/authorized_keys:/etc/authorized_keys
    tty: true
    links:
    - r-nerisk-postgis:pgis
    labels:
      io.rancher.container.pull_image: always
  r-nerisk-postgis:
    image: jeanpommier/padre-postgis:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    stdin_open: true
    volumes:
    - r-nerisk-postgisdata-volume:/var/lib/postgresql/data/pgdata
    tty: true
    labels:
      io.rancher.container.pull_image: always
