version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.http: 'true'
  SSL-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.https: 'true'
  httpd:
    image: jeanpommier/padre-httpd:latest
    environment:
      APACHE_SERVERNAME: ${DOMAIN_URL}
      POSTGRES_HOST: pgis
      POSTGRES_PORT: '5432'
      POSTGRES_DEFAULTDB: geodata
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/www_data:/var/www/html/"
    tty: true
    links:
      - postgis:pgis
    labels:
      fr.pigeo.container-type: httpd
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geoportal:
    image: jeanpommier/padre-geonetwork:latest
    environment:
      - "POSTGRES_DB_HOST: pg"
      - "POSTGRES_DB_USERNAME: padre"
      - "POSTGRES_DB_PASSWORD: padre"
      - "DATA_DIR: /padre/geonetwork_data"
      - "GEOSERVER_NS:${GEOSERVER_NS}"
      - "PROJECT_URL:${DOMAIN_URL}"
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geonetwork_data:/padre/geonetwork_data"
    tty: true
    links:
      - postgis:pg
    labels:
      fr.pigeo.container-type: Geonetwork
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geodash:
    image: jeanpommier/padre-geodash:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
    tty: true
    links:
      - postgis:pg
    labels:
      fr.pigeo.container-type: Geodash
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  owncloud:
    image: jeanpommier/padre-owncloud:latest
    environment:
      OWNCLOUD_DOMAIN: ${DOMAIN_URL}
      OWNCLOUD_SUB_URL: /owncloud
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/owncloud_data:/mnt/data"
  odkaggregate:
    image: jeanpommier/padre-odkaggregate:latest
    environment:
      DB_HOSTNAME: pgis
      DB_USER: padre
      DB_PASSWORD: padre
      DB_DATABASE: geodata
      DB_SCHEMA: odk1
      DB_PORT: '5432'
      ODK_HOSTNAME: ${DOMAIN_URL}
      ODK_PORT: '80'
    stdin_open: true
    links:
      - postgis:pgis
    labels:
      fr.pigeo.container-type: owncloud
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geoserver:
    image: jeanpommier/padre-geoserver:latest
    environment:
      GEOSERVER_DATA_DIR: /padre/geoserver_data
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
      - "/home/projects/${PROJECT_ID}/geoserver_data:/padre/geoserver_data"
    tty: true
    links:
      - postgis:pgis
    labels:
      fr.pigeo.container-type: GeoServer
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  ssh:
    image: jeanpommier/padre-commandline:latest
    environment:
      SSH_USERS: jean:1000:1000,florent:1001:1001,philippe:1002:1002,raincell:1003:1003
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/sshd_config:/etc/ssh"
      - "/home/projects/${PROJECT_ID}/sshd_home:/home"
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
      - "/home/projects/${PROJECT_ID}/geoserver_data:/padre/geoserver_data"
      - "/home/projects/${PROJECT_ID}/geonetwork_data:/padre/geonetwork_data"
      - "/home/projects/${PROJECT_ID}/www_data:/padre/www_data"
      - "/home/projects/${PROJECT_ID}/owncloud_data:/padre/owncloud_data"
      - /etc/authorized_keys:/etc/authorized_keys
    tty: true
    links:
      - postgis:pgis
    labels:
      fr.pigeo.container-type: SSHD
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  postgis:
    image: jeanpommier/padre-postgis:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD:
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/postgis_data:/var/lib/postgresql/data/pgdata"
    tty: true
    labels:
      fr.pigeo.container-type: PostGis
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
