version: '2'
services:
  SSL-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      web.https: 'true'
  httpd:
    image: pigeosolutions/padre-httpd:latest
    environment:
      APACHE_SERVERNAME: ${DOMAIN_URL}
      POSTGRES_HOST: pgis
      POSTGRES_PORT: '5432'
      POSTGRES_DEFAULTDB: geodata
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/www_data:/var/www/html/"
    tty: true
    links:
      - postgis:pgis
    labels:
      logspout: enable
      fr.pigeo.container-type: httpd
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geonetwork:
    image: pigeosolutions/padre-geonetwork:latest
    environment:
      POSTGRES_DB_HOST: pg
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
      DATA_DIR: /padre/geonetwork_data
      GEOSERVER_NS: ${GEOSERVER_NS}
      PROJECT_URL: ${DOMAIN_URL}
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geonetwork_data:/padre/geonetwork_data"
    tty: true
    links:
      - postgis:pg
    labels:
      logspout: enable
      fr.pigeo.container-type: Geonetwork
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geodash:
    image: pigeosolutions/padre-geodash:latest
    environment:
      POSTGRES_DB_USERNAME: padre
      POSTGRES_DB_PASSWORD: padre
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
      - "/home/projects/${PROJECT_ID}/geoserver_data:/padre/geoserver_data"
    tty: true
    links:
      - postgis:pg
    labels:
      logspout: enable
      fr.pigeo.container-type: Geodash
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  owncloud:
    image: pigeosolutions/padre-owncloud:latest
    environment:
      OWNCLOUD_DOMAIN: ${DOMAIN_URL}
      OWNCLOUD_SUB_URL: /owncloud
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/owncloud_data:/mnt/data"
    labels:
      logspout: enable
      fr.pigeo.container-type: owncloud
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  odkaggregate:
    image: pigeosolutions/padre-odkaggregate:latest
    environment:
      DB_HOSTNAME: pgis
      DB_USER: padre
      DB_PASSWORD: padre
      DB_DATABASE: geodata
      DB_SCHEMA: odk1
      DB_PORT: '5432'
      ODK_HOSTNAME: ${DOMAIN_URL}
      ODK_PORT: '80'
      ODK_PORT_SECURE: '443'
      ODK_CHANNELTYPE: 'ANY_CHANNEL'
    stdin_open: true
    links:
      - postgis:pgis
    labels:
      logspout: enable
      fr.pigeo.container-type: odkaggregate
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  geoserver:
    image: pigeosolutions/padre-geoserver:latest
    environment:
      GEOSERVER_DATA_DIR: /padre/geoserver_data
      GEOSERVER_FILEBROWSER_HIDEFS: true
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
      - "/home/projects/${PROJECT_ID}/geoserver_data:/padre/geoserver_data"
    tty: true
    links:
      - postgis:pgis
    labels:
      logspout: enable
      fr.pigeo.container-type: GeoServer
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  ssh:
    image: pigeosolutions/padre-commandline:latest
    environment:
      SSH_USERS: jpommier:1000:2000,fgravin:1001:2000,prapaport:1002:2000,raincell:1003:1003
      PROJECTID: ${PROJECT_ID}
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/sshd_config:/etc/ssh"
      - "/home/projects/${PROJECT_ID}/sshd_home:/home"
      - "/home/projects/${PROJECT_ID}/geodata:/padre/geodata"
      - "/home/projects/${PROJECT_ID}/processing:/padre/processing"
      - "/home/projects/${PROJECT_ID}/geoserver_data:/padre/geoserver_data"
      - "/home/projects/${PROJECT_ID}/geonetwork_data:/padre/geonetwork_data"
      - "/home/projects/${PROJECT_ID}/www_data:/padre/www_data"
      - "/home/projects/${PROJECT_ID}/owncloud_data:/padre/owncloud_data"
      - "/home/projects/${PROJECT_ID}/cron_crontabs:/var/spool/cron/crontabs"
      - /etc/authorized_keys:/etc/authorized_keys
    tty: true
    links:
      - postgis:pgis
    labels:
      logspout: enable
      fr.pigeo.container-type: SSHD
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
  postgis:
    image: pigeosolutions/padre-postgis:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD:
    stdin_open: true
    volumes:
      - "/home/projects/${PROJECT_ID}/postgis_data:/var/lib/postgresql/data/pgdata"
      - "/home/projects/${PROJECT_ID}/postgis_backups:/backups"
    tty: true
    labels:
      logspout: enable
      fr.pigeo.container-type: PostGis
      fr.pigeo.project: ${PROJECT_ID}
      fr.pigeo.product: Padre v2
      io.rancher.container.pull_image: always
