version: '2'
services:
  r-gabonmines-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ga.pigeo.fr
        path: /geoserver
        priority: 1
        protocol: http
        service: r-gabonmines-geoserver
        source_port: 80
        target_port: 8080
      - hostname: ga.pigeo.fr
        path: /geonetwork
        priority: 3
        protocol: http
        service: r-gabonmines-geoportal
        source_port: 80
        target_port: 8080
      - hostname: ga.pigeo.fr
        path: /ODKAggregate
        priority: 4
        protocol: http
        service: r-gabonmines-odkaggregate
        source_port: 80
        target_port: 8080
      - hostname: ga.pigeo.fr
        path: /owncloud
        priority: 5
        protocol: http
        service: r-gabonmines-owncloud
        source_port: 80
        target_port: 80
      - hostname: ga.pigeo.fr
        path: /
        priority: 6
        protocol: http
        service: r-gabonmines-httpd
        source_port: 80
        target_port: 80
      - priority: 7
        protocol: tcp
        service: r-gabonmines-ssh
        source_port: 22
        target_port: 22
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  r-gabonmines-SSL-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ga.pigeo.fr
        path: /geoserver
        priority: 1
        protocol: http
        service: r-gabonmines-geoserver
        source_port: 8080
        target_port: 8080
      - hostname: ga.pigeo.fr
        path: /geoserver
        priority: 2
        protocol: http
        service: r-gabonmines-geoserver
        source_port: 80
        target_port: 8080
      - hostname: ga.pigeo.fr
        path: /
        priority: 3
        protocol: http
        service: r-gabonmines-httpd
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000  
  r-gabonmines-httpd:
    scale: 1
    start_on_create: true
  r-gabonmines-geoportal:
    scale: 1
    start_on_create: false
  r-gabonmines-owncloud:
    scale: 1
    start_on_create: true
  r-gabonmines-odkaggregate:
    scale: 1
    start_on_create: true
  r-gabonmines-geoserver:
    scale: 1
    start_on_create: false
  r-gabonmines-ssh:
    scale: 1
    start_on_create: true
  r-gabonmines-postgis:
    scale: 1
    start_on_create: true
