version: '2'
services:
  SSL-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: "${DOMAIN_URL}"
        path: /geoserver
        priority: 1
        protocol: http
        service: geoserver
        source_port: 8080
        target_port: 8080
      - hostname: "${DOMAIN_URL}"
        path: /geoserver
        priority: 2
        protocol: http
        service: geoserver
        source_port: 80
        target_port: 8080
      - hostname: "${DOMAIN_URL}"
        path: /ODKAggregate
        priority: 3
        protocol: http
        service: odkaggregate
        source_port: 80
        target_port: 8080
      - hostname: "${DOMAIN_URL}"
        path: /ODKAggregate
        priority: 3
        protocol: http
        service: odkaggregate
        source_port: 8080
        target_port: 8080
      - hostname: "${DOMAIN_URL}"
        path: /owncloud
        priority: 4
        protocol: http
        service: owncloud
        source_port: 80
        target_port: 80
      - hostname: "${DOMAIN_URL}"
        path: /geonetwork
        priority: 5
        protocol: http
        service: geonetwork
        source_port: 80
        target_port: 8080
      - hostname: "${DOMAIN_URL}"
        path: /
        priority: 6
        protocol: http
        service: httpd
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  httpd:
    scale: 1
    start_on_create: true
  geoportal:
    scale: 1
    start_on_create: false
  owncloud:
    scale: 1
    start_on_create: true
  odkaggregate:
    scale: 1
    start_on_create: true
  geoserver:
    scale: 1
    start_on_create: false
  ssh:
    scale: 1
    start_on_create: true
  postgis:
    scale: 1
    start_on_create: true
