version: '2'
services:
  r-nerisk-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ne-risk.pigeosolutions.fr
        path: /geoserver
        priority: 1
        protocol: http
        service: r-nerisk-geoserver
        source_port: 80
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /geonetwork
        priority: 3
        protocol: http
        service: r-nerisk-geoportal
        source_port: 80
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /geodash
        priority: 3
        protocol: http
        service: r-nerisk-geodash
        source_port: 80
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /ODKAggregate
        priority: 4
        protocol: http
        service: r-nerisk-odkaggregate
        source_port: 80
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /owncloud
        priority: 5
        protocol: http
        service: r-nerisk-owncloud
        source_port: 80
        target_port: 80
      - hostname: ne-risk.pigeosolutions.fr
        path: /
        priority: 6
        protocol: http
        service: r-nerisk-httpd
        source_port: 80
        target_port: 80
      - priority: 7
        protocol: tcp
        service: r-nerisk-ssh
        source_port: 22
        target_port: 22
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  r-nerisk-SSL-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ne-risk.pigeosolutions.fr
        path: /geoserver
        priority: 1
        protocol: http
        service: r-nerisk-geoserver
        source_port: 8080
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /geoserver
        priority: 2
        protocol: http
        service: r-nerisk-geoserver
        source_port: 80
        target_port: 8080
      - hostname: ne-risk.pigeosolutions.fr
        path: /
        priority: 3
        protocol: http
        service: r-nerisk-httpd
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000  
  r-nerisk-httpd:
    scale: 1
    start_on_create: true
  r-nerisk-geoportal:
    scale: 1
    start_on_create: false
  r-nerisk-owncloud:
    scale: 1
    start_on_create: true
  r-nerisk-odkaggregate:
    scale: 1
    start_on_create: true
  r-nerisk-geoserver:
    scale: 1
    start_on_create: false
  r-nerisk-ssh:
    scale: 1
    start_on_create: true
  r-nerisk-postgis:
    scale: 1
    start_on_create: true
