spring:
  datasource:
    url: jdbc:postgresql://pgis:5432/pialert
    username: padre
    password: padre
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
